### ISSUE TITLE
Support discard for blkio

### ISSUE THREAD

**Issue by liubin** [kata-containers/cgroups-rs#109]
Now we use a fixed format to parse io service data, but it may change.

https://github.com/kata-containers/cgroups-rs/blob/a45ecf08846aebdef1bbcb0507f906406b9a4934/src/blkio.rs#L103-L107

Should implement like [runc](https://github.com/opencontainers/runc/blob/32d741358f8fc843b267608b2b684711a8dcaa2a/libcontainer/cgroups/fs/blkio.go#L111) to support different version kernels.

**Comment by singhwang** [comment]
@liubin In addition, the question you mentioned is "Note that virtiofs has no blkio stats, you may need some block devices." I want to ask again, the shared_fs of kata can only use virtio-9p, virtio-fs or virtio-fs-nydus , I don't quite understand what you said about using block devices here.
