### ISSUE TITLE
Public access to path of memory controller

### ISSUE THREAD

**Issue by itamarst** [kata-containers/cgroups-rs#24]
**Which feature do you think can be improved?**

This package is great insofar is it works both on cgroups v1 and v2. Thank you! However, it's a little slow for my needs. In particular, I am getting memory stats. Right now the way `memory_stat()` works is it opens a whole bunch of files, and does a whole bunch of parsing, much of which is not relevant to me. It's pretty slow (for my needs, this is happening occasionally but on a critical code path).

**How can it be improved?**

As a workaround to API redesign/improvements, just making the controller path public (or `open_path()` public) would allow for me to open the two files I need, and just rely on the v1 vs v2 + controller mapping code in the package.

**Additional Information**

An API for getting e.g. memory info that only got specific attributes would be handy, right now I'm forced to load everything that fits in `memory_stat()` output. But that would be more work for you, and this change is just adding a 2-line method, say.

**Comment by Tim-Zhang** [comment]
@lifupan @liubin What do you think about this suggestion? I think make open_path public is ok and useful.

**Comment by liubin** [comment]
I think this is not a bad idea to give cgroups path to user.
And I also suggest provide a function `with_file` that user can use it like this:

```
cg.with_file("memory.stat", || {
  do_some_custom_parse();
})
```

**Comment by Tim-Zhang** [comment]
@itamarst I think you can use path() https://github.com/kata-containers/cgroups-rs/blob/master/src/lib.rs#L244 to get the path and read the file.

**Comment by itamarst** [comment]
Looks promising, added to my todo list to try.
