### ISSUE TITLE
panic when parse memory stats with old linux kernel

### ISSUE THREAD

**Issue by Burning1020** [kata-containers/cgroups-rs#36]
**Env**
```
kernel version: 3.10.0
cgroup version: v1
```
**Describe the bug**
1. call `memory_stat()` function at src/memory.rs
2. go in to `parse_numa_stat()` function
3. the first 4 arrtibutes work well but panic at `let hier_total_line = ls.next().unwrap();`
4. check `memory.numa_stat` file under /sys/fs/cgrop, i couldn't find any words start with **hierarchical_\*\***, maybe caused by old kernel

**Expected behavior**
return default value when get None

**Additional context**
suggest change unwrap() to unwrap_or()
this bug will happen when call `parse_oom_control` function

**Comment by ariel-adam** [comment]
@bergwolf is this repository still used or should we refer @Burning1020 to another repository?

**Comment by bergwolf** [comment]
@ariel-adam yes, it is still in use. Sorry for the delay due to Chinese new year.

@Burning1020 Sounds like a kernel compatibility issue. What kernel version are you using?

**Comment by jodh-intel** [comment]
Sounds like this should be reproducible on a CentOS 7 system, which also uses a 3.10.0 kernel.

**Comment by Burning1020** [comment]
thanks guys!
however, as mentioned before, it is possiable that calling `parse_oom_control` occurs same issue, plz check and fix it!

**Comment by bergwolf** [comment]
You are right! Thanks for pointing out the missing part. I've reopened the issue and posted a fix. Please see if it fixed your issue. Thanks!

**Comment by Burning1020** [comment]
@bergwolf  Yes, it fixes my problem! thank you
