### ISSUE TITLE
Support rootless cgroup v2

### ISSUE THREAD

**Issue by huanghongxun** [kata-containers/cgroups-rs#42]
Currently cgroups-rs manages cgroups in privilged mode. To support rootless containers, this library should ask for permission of cgroup management in unprivileged mode.

Related implementations, which requires communicating with systemd, asking for a path to rootless cgroup 2 hierarchy, use it for relative path.
github.com/opencontainers/runc/pull/2281

**Comment by ariel-adam** [comment]
@huanghongxun could you please help clarify what you would you need?

**Comment by jodh-intel** [comment]
Hi @huanghongxun - Thanks for raising, but I'm sligthly confused :confused: The cgroups-rs crate is only used by the Kata 2.x agent which runs inside the VM. Are you talking about running rootless inside the VM?

It's worth pointing out that the rust Kata agent can either run as a systemd service (`kata-containers.img` in the `configuration.toml` file) or the agent  can run as the init process (PID 1) if you use `kata-containers-initrd.img`. In the latter scenario, there is no systemd in the image to communicate with.

**Comment by lifupan** [comment]
Hi @huanghongxun 

Just as @jodh-intel said, the cgroup-rs is only used in kata guest instead of host, so what's your case based on rootless cgroup-rs?  BTW, if you are interested in contributing on it, the patches are welcomed.

**Comment by Tim-Zhang** [comment]
@huanghongxun Do you have any updates? if not I will close the issue later.
