### ISSUE TITLE
Add optional serde support for statistics structs

### ISSUE THREAD

**Issue by flxo** [kata-containers/cgroups-rs#54]
**Is your feature request related to a problem? Please describe.**

Gathering statistics via cgroups is great. They cover hierarchies of processes without the need to scan a list of task etc. The statistics contains a huge amount of values. Copying the values to a custom struct or merging them into a hashmap is manual work. Using the exact same structure and names as in the cgroup files has the advantage that the values are also documented. 
The structs defined for e.g `memory` or `blkio` do not derive from Serdes `Serialize` and `Deserialize` which would allow to directly serialise stats generated with e.g `blkio::BlkIoController::blkio`.

**Describe the solution you'd like**

Add an optional crate dependency `serde` with feature `derive`:

```toml
serde = { version = "1.0", features = ["derive"], optional = true }
```

Derive the statistics structs from `serde::Serialize` and `serde::Deserialize` if the feature `serde` is enabled e.g:

```rust
/// State of and statistics gathered by the kernel about the memory usage of the control group's
/// tasks.
#[derive(Debug)]
#[cfg_attr(feature="serde", derive(serde::Serialize, serde::Deserialize))]
pub struct Memory {
    /// How many times the limit has been hit.
    pub fail_cnt: u64,
    /// The limit in bytes of the memory usage of the control group's tasks.
    pub limit_in_bytes: i64,
    /// The current usage of memory by the control group's tasks.
    pub usage_in_bytes: u64,
...
```

See https://github.com/serde-rs/serde/issues/1021.

**Describe alternatives you've considered**

Following [Deriving De/Serialize for type in a different crate](https://serde.rs/remote-derive.html)

**Additional context**

A PR should be almost non invasive, because without the feature enabled there shouldn't be any change.

**Comment by flxo** [comment]
It's also probably worth to thing also about doing the same for [Resources](https://docs.rs/cgroups-rs/0.2.6/cgroups_rs/struct.Resources.html) and all included structs...

**Comment by flxo** [comment]
Could someone please have a look and give a hint if such a patch would be appreciated? 

The PR itself for this issues would be rather simple and I could push it on request.

**Comment by jodh-intel** [comment]
Thanks for suggesting this @flxo. I think this makes a lot of sense.

/cc @liubin, @Tim-Zhang, @lifupan, @bergwolf.

**Comment by lifupan** [comment]
Thanks @flxo， it's reasonable to add them and the PR is welcomed.
