### ISSUE TITLE
Release 0.2.10 on crate.io

### ISSUE THREAD

**Issue by flxo** [kata-containers/cgroups-rs#80]
Hello,

I want to kindly ask if it's possible to push 0.2.10 on crates.io?

My project is depending on #79 (merged - thanks!) and I'd like to release on crates.io as well but I'm block because of the [git dependency on cgroups-rs](https://github.com/esrlabs/northstar/blob/a7f7c1e793d25a26423ce3304adb72aae10a443e/northstar-runtime/Cargo.toml#L23).

Thanks!

@flxo

**Comment by Tim-Zhang** [comment]
Hi @flxo https://crates.io/crates/cgroups-rs/0.2.10 has been released on Jun 29. Sorry for the late response.
